- name: Create isucari directory
  become: yes
  become_user: isucon
  file:
    path=/home/isucon/isucari
    state=directory

# Following is Copied from https://github.com/matsuu/ansible-isucon9-qualify/blob/master/roles/dev.deploy/tasks/main.yml

- name: add packages
  become: yes
  package:
    name:
      - git
      - rsync
    state: present

- name: clone git repository
  become: yes
  become_user: isucon
  git:
    repo: https://github.com/isucon/isucon9-qualify.git
    dest: /tmp/isucon9-qualify
    depth: 1    

- name: Deploy isucari
  become: yes
  become_user: isucon
  shell: |
    rsync -a --delete --exclude=.git --exclude=.gitignore --exclude=provisioning /tmp/isucon9-qualify/ /home/isucon/isucari/
  args:
    creates: /home/isucon/isucari/initial-data    

## 以下は公式の名残 https://github.com/isucon/isucon9-qualify/blob/master/provisioning/roles/dev.deploy/tasks/main.yml#L20

# - name: Deploy isucari
#   become: yes
#   synchronize:
#     src: ../../../../
#     dest: /home/isucon/isucari
#     delete: yes
#     recursive: yes
#     rsync_opts:
#       - "--exclude=.git"
#       - "--exclude=.gitignore"
#       - "--exclude=provisioning"

# - name: Chown isucon
#   become: yes
#   become_user: root
#   file:
#     dest: /home/isucon/isucari
#     owner: isucon
#     group: isucon
#     mode: 0755
#     recurse: yes
