- name: Create isucon group
  group:
    name: isucon
    gid: 1001
    state: present
    system: no

- name: Create isucon user
  user:
    name: isucon
    uid: 1001
    group: isucon
    password: isucon
    home: /home/isucon
    shell: /bin/bash
    state: present
    system: no
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    ssh_key_passphrase: ""
    force: no

- name: Set authorized key of myself to allow other servers to access with same user
  file:
    path: /home/isucon/.ssh/authorized_keys
    state: touch
    owner: isucon
    group: isucon
    mode: 0600

- name: Insert content to the authorized key file
  shell: |
    cat /home/isucon/.ssh/id_rsa.pub >> /home/isucon/.ssh/authorized_keys

- name: Add sudoers
  copy:
    content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
    dest: /etc/sudoers.d/90-isucon-user
    owner: root
    group: root
    mode: 0440
